# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Racconti brevi di Alessio Periloso
tagline:             ''
description:         ''
url:                 http://periloso.github.io/novels
baseurl:             ''
paginate:            5
default_locale:      'it_IT'
markdown:            kramdown
kramdown:
  input:             GFM   # Enable GitHub Flavored Markdown (fenced code blocks)

# About/contact
author:
  name:              Alessio Periloso
  url:               https://periloso.it
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
